version: '3'
services:
  app:
    build: .
    ports:
      - "8081:3000"
    volumes:
      - ./:/var/www/app
    command:
      sh -c 'npm i && node server.js'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://cache
    links:
      - redis      
      
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  
   
