app:
          build: ./
          volumes:
                    - ./:/var/www/app
          ports:
                    - 8081:3000
          environment:
                    - NODE_ENV=development
                    - PORT=8081
          command:
                    sh -c 'npm i && node server.js' 
